pipeline:
  name: NX Affected IAC Quality Check
  identifier: nx_affected_iac_quality_check
  projectIdentifier: Proof_Web
  orgIdentifier: default
  tags:
    repo: foundations-iac
    type: quality-check
    tool: nx
  template:
    templateRef: account.template_nx_affected_iac_quality_check
    versionLabel: v1.0.0
    gitBranch: main
    templateInputs:
      properties:
        ci:
          codebase:
            repoName: <+input>
            build: <+input>
