pipeline:
  name: NX Affected IAC Quality Check
  identifier: nx_affected_iac_quality_check
  projectIdentifier: Proof_Web
  orgIdentifier: default
  tags:
    repo: foundations-iac
    type: quality-check
    tool: nx
  properties:
    ci:
      codebase:
        connectorRef: account.VICTORSEARAORG
        repoName: foundations-iac
        build: <+input>
  stages:
    - stage:
        name: IAC Quality Check
        identifier: iac_quality_check
        description: Run quality and security checks on affected IAC modules
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            paths:
              - /root/.local/share/pnpm/store
              - node_modules
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              # ===========================================
              # Step Group 1: Setup Dependencies
              # ===========================================
              - stepGroup:
                  name: Setup Dependencies
                  identifier: setup_dependencies
                  steps:
                    # 1.1 Install Node.js using .nvmrc
                    - step:
                        type: Run
                        name: Install Node
                        identifier: install_node
                        spec:
                          shell: Bash
                          command: |
                            echo "=== Installing Node.js ==="
                            
                            # Read Node version from .nvmrc
                            if [ -f ".nvmrc" ]; then
                              NODE_VERSION=$(cat .nvmrc | tr -d 'v' | tr -d '\n' | tr -d ' ')
                              echo "Found .nvmrc with version: $NODE_VERSION"
                            else
                              echo "Error: .nvmrc file not found"
                              exit 1
                            fi
                            
                            # Install nvm if not present
                            export NVM_DIR="$HOME/.nvm"
                            if [ ! -d "$NVM_DIR" ]; then
                              curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
                            fi
                            
                            # Load nvm
                            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
                            
                            # Install and use the specified Node version
                            nvm install $NODE_VERSION
                            nvm use $NODE_VERSION
                            nvm alias default $NODE_VERSION
                            
                            # Verify installation
                            echo "Node version: $(node --version)"
                            echo "NPM version: $(npm --version)"
                            
                            # Export paths for subsequent steps
                            echo "export NVM_DIR=\"$HOME/.nvm\"" >> $HOME/.bashrc
                            echo "[ -s \"\$NVM_DIR/nvm.sh\" ] && \\. \"\$NVM_DIR/nvm.sh\"" >> $HOME/.bashrc

                    # 1.2 Install pnpm using .pnpm-version
                    - step:
                        type: Run
                        name: Install Pnpm
                        identifier: install_pnpm
                        spec:
                          shell: Bash
                          command: |
                            echo "=== Installing pnpm ==="
                            
                            # Load nvm
                            export NVM_DIR="$HOME/.nvm"
                            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
                            
                            # Read pnpm version from .pnpm-version
                            if [ -f ".pnpm-version" ]; then
                              PNPM_VERSION=$(cat .pnpm-version | tr -d '\n' | tr -d ' ')
                              echo "Found .pnpm-version with version: $PNPM_VERSION"
                            else
                              echo "Error: .pnpm-version file not found"
                              exit 1
                            fi
                            
                            # Install pnpm using corepack or npm
                            corepack enable 2>/dev/null || true
                            npm install -g pnpm@$PNPM_VERSION
                            
                            # Verify installation
                            echo "pnpm version: $(pnpm --version)"

                    # 1.3 Setup NX_HEAD and NX_BASE for affected commands
                    - step:
                        type: Run
                        name: Setup NX Environment
                        identifier: setup_nx_env
                        spec:
                          shell: Bash
                          command: |
                            echo "=== Setting up NX environment variables ==="
                            
                            # For Pull Requests, set NX_BASE and NX_HEAD
                            if [ -n "<+codebase.prNumber>" ] && [ "<+codebase.prNumber>" != "null" ]; then
                              echo "Pull Request detected: #<+codebase.prNumber>"
                              
                              # NX_BASE: The target branch of the PR (main, develop, etc.)
                              NX_BASE="origin/<+codebase.targetBranch>"
                              
                              # NX_HEAD: The current commit SHA
                              NX_HEAD="<+codebase.commitSha>"
                            else
                              echo "Not a PR build, using default affected behavior"
                              NX_BASE="origin/main~1"
                              NX_HEAD="HEAD"
                            fi
                            
                            echo "NX_BASE=$NX_BASE"
                            echo "NX_HEAD=$NX_HEAD"
                            
                            # Export for subsequent steps
                            export NX_BASE
                            export NX_HEAD
                          outputVariables:
                            - name: NX_BASE
                            - name: NX_HEAD

                    # 1.4 Install Pre-requirements (parallel installation)
                    - parallel:
                        - step:
                            type: Run
                            name: Install OpenTofu
                            identifier: install_opentofu
                            spec:
                              shell: Bash
                              command: |
                                echo "=== Installing OpenTofu ==="
                                
                                # Install OpenTofu via official installer script
                                curl --proto '=https' --tlsv1.2 -fsSL https://get.opentofu.org/install-opentofu.sh -o install-opentofu.sh
                                chmod +x install-opentofu.sh
                                ./install-opentofu.sh --install-method standalone --skip-verify
                                rm install-opentofu.sh
                                
                                # Add to PATH
                                export PATH="$HOME/.opentofu/bin:$PATH"
                                echo 'export PATH="$HOME/.opentofu/bin:$PATH"' >> $HOME/.bashrc
                                
                                # Verify installation
                                tofu --version

                        - step:
                            type: Run
                            name: Install TFLint
                            identifier: install_tflint
                            spec:
                              shell: Bash
                              command: |
                                echo "=== Installing TFLint ==="
                                
                                # Install TFLint
                                curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
                                
                                # Verify installation
                                tflint --version

                        - step:
                            type: Run
                            name: Install Checkov
                            identifier: install_checkov
                            spec:
                              shell: Bash
                              command: |
                                echo "=== Installing Checkov ==="
                                
                                # Install Checkov via pip
                                pip3 install --user checkov
                                
                                # Add to PATH
                                export PATH="$HOME/.local/bin:$PATH"
                                echo 'export PATH="$HOME/.local/bin:$PATH"' >> $HOME/.bashrc
                                
                                # Verify installation
                                checkov --version

                        - step:
                            type: Run
                            name: Install terraform-docs
                            identifier: install_terraform_docs
                            spec:
                              shell: Bash
                              command: |
                                echo "=== Installing terraform-docs ==="
                                
                                # Get latest version
                                TERRAFORM_DOCS_VERSION="v0.18.0"
                                
                                # Download and install
                                curl -sSLo ./terraform-docs.tar.gz https://github.com/terraform-docs/terraform-docs/releases/download/${TERRAFORM_DOCS_VERSION}/terraform-docs-${TERRAFORM_DOCS_VERSION}-linux-amd64.tar.gz
                                tar -xzf terraform-docs.tar.gz
                                chmod +x terraform-docs
                                mkdir -p $HOME/.local/bin
                                mv terraform-docs $HOME/.local/bin/
                                rm terraform-docs.tar.gz
                                
                                # Verify installation
                                $HOME/.local/bin/terraform-docs --version

              # ===========================================
              # Step 2: Install Dependencies
              # ===========================================
              - step:
                  type: Run
                  name: Install Dependencies
                  identifier: install_dependencies
                  spec:
                    shell: Bash
                    command: |
                      echo "=== Installing project dependencies ==="
                      
                      # Load nvm
                      export NVM_DIR="$HOME/.nvm"
                      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
                      
                      # Install dependencies
                      pnpm install --frozen-lockfile
                      
                      echo "Dependencies installed successfully"

              # ===========================================
              # Steps 3 & 4: Quality Check and Security Check (Parallel)
              # ===========================================
              - parallel:
                  - step:
                      type: Run
                      name: Quality Check
                      identifier: quality_check
                      spec:
                        shell: Bash
                        command: |
                          echo "=== Running Quality Checks (affected projects) ==="
                          
                          # Load nvm and tools
                          export NVM_DIR="$HOME/.nvm"
                          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
                          export PATH="$HOME/.opentofu/bin:$HOME/.local/bin:$PATH"
                          
                          # Set NX environment variables for affected detection
                          export NX_BASE="<+execution.steps.setup_dependencies.steps.setup_nx_env.output.outputVariables.NX_BASE>"
                          export NX_HEAD="<+execution.steps.setup_dependencies.steps.setup_nx_env.output.outputVariables.NX_HEAD>"
                          
                          echo "NX_BASE: $NX_BASE"
                          echo "NX_HEAD: $NX_HEAD"
                          
                          # Run quality checks on affected projects
                          # This runs fmt, validate, and lint targets
                          pnpm tofu:affected
                          
                          echo "Quality checks completed successfully"
                        envVariables:
                          NX_BASE: <+execution.steps.setup_dependencies.steps.setup_nx_env.output.outputVariables.NX_BASE>
                          NX_HEAD: <+execution.steps.setup_dependencies.steps.setup_nx_env.output.outputVariables.NX_HEAD>

                  - step:
                      type: Run
                      name: Security Check
                      identifier: security_check
                      spec:
                        shell: Bash
                        command: |
                          echo "=== Running Security Checks (affected projects) ==="
                          
                          # Load nvm and tools
                          export NVM_DIR="$HOME/.nvm"
                          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
                          export PATH="$HOME/.opentofu/bin:$HOME/.local/bin:$PATH"
                          
                          # Set NX environment variables for affected detection
                          export NX_BASE="<+execution.steps.setup_dependencies.steps.setup_nx_env.output.outputVariables.NX_BASE>"
                          export NX_HEAD="<+execution.steps.setup_dependencies.steps.setup_nx_env.output.outputVariables.NX_HEAD>"
                          
                          echo "NX_BASE: $NX_BASE"
                          echo "NX_HEAD: $NX_HEAD"
                          
                          # Run security checks on affected projects
                          pnpm nx affected -t security
                          
                          echo "Security checks completed successfully"
                        envVariables:
                          NX_BASE: <+execution.steps.setup_dependencies.steps.setup_nx_env.output.outputVariables.NX_BASE>
                          NX_HEAD: <+execution.steps.setup_dependencies.steps.setup_nx_env.output.outputVariables.NX_HEAD>

  # ===========================================
  # Notification Rules (Pipeline Status Reporting)
  # ===========================================
  notificationRules:
    - name: Pipeline Status Notification
      identifier: pipeline_status_notification
      pipelineEvents:
        - type: PipelineSuccess
        - type: PipelineFailed
      notificationMethod:
        type: Slack
        spec:
          webhookUrl: <+input>
      enabled: true
