pipeline:
  name: NX Affected IAC Quality Check
  identifier: nx_affected_iac_quality_check
  projectIdentifier: Proof_Web
  orgIdentifier: default
  tags:
    repo: foundations-iac
    type: quality-check
    tool: nx
  properties:
    ci:
      codebase:
        connectorRef: account.VICTORSEARAORG
        repoName: <+trigger.payload.repository.name>
        build: <+input>
  stages:
    - stage:
        name: Testing pipeline connection
        identifier: testing_pipeline_connection
        type: CI
        description: A simple stage to test pipeline connection from trigger
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: false
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            architecture: AMD64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  name: Echo pipeline connection successful
                  identifier: echo_pipeline_connection_successful
                  type: Run
                  spec:
                    shell: Bash
                    command: |
                      echo "Pipeline connection successful!"
#   template:
#     templateRef: account.template_nx_affected_iac_quality_check
#     versionLabel: v1.0.0
#     gitBranch: main
#     templateInputs:
#       properties:
#         ci:
#           codebase:
#             connectorRef: account.VICTORSEARAORG
#             repoName: <+trigger.payload.repository.name>
#             build: <+input>
