trigger:
  name: PR Quality Check Trigger
  identifier: pr_quality_check_trigger
  description: Triggers quality and security checks on Pull Requests targeting main branch
  projectIdentifier: Proof_Web
  orgIdentifier: default
  pipelineIdentifier: nx_affected_iac_quality_check
  pipelineBranchName: main
  enabled: true
  tags:
    type: ci
    event: pull-request
  source:
    type: Webhook
    spec:
      type: Github
      spec:
        type: PullRequest
        spec:
          connectorRef: account.VICTORSEARAORG
          repoName: foundations-iac
          autoAbortPreviousExecutions: true
          payloadConditions:
            - key: targetBranch
              operator: Equals
              value: main
          headerConditions: []
          jexlCondition: ""
          actions:
            - Open
            - Reopen
            - Synchronize
            - Edit
  inputSetRefs:
    - pr_run_input_set
